server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "67"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HQ
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
