server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "${LAVALINK_PASSWORD}"
    sources:
      youtube: false # MUST be false so the plugin can take over
      bandcamp: true
      soundcloud: true
      twitch: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_MUSIC
      - ANDROID_VR
      - WEB
      - TVHTML5_SIMPLY
    oauth:
      enabled: true
      refreshToken: "1//0gWzqEX8y_dEXCgYIARAAGBASNwF-L9IrPKe-uqDpbCunzcnyVzyywf6vS_c02Nde6Huf0-BxwC_ltWuqVaalrJQFTxJ2cwwvCD8"
logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO  
